version: '3'

services:
  mysql:
    container_name: bbabbico
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: bbabbico
      MYSQL_PASSWORD: bbabbico
      MYSQL_DATABASE: bbabbico
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  application:
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - TZ="Asia/Seoul"