spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/bbabbico
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bbabbico
    password: bbabbico

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

debug: true